<?php
/**
 * PgsqlAdapter — PostgreSQL 数据库适配器 (PDO)
 *
 * implements DatabaseInterface, 替换 MysqlAdapter 即可切换数据库.
 * 用法: new PgsqlAdapter($host, $user, $pass, $db, $port)
 *
 * SQL 方言差异 (业务代码需注意):
 *   MySQL `table` → PostgreSQL "table"
 *   AUTO_INCREMENT → SERIAL / GENERATED BY DEFAULT AS IDENTITY
 *   utf8mb4 → UTF8
 *   REPLACE INTO → INSERT ... ON CONFLICT DO UPDATE
 */
declare(strict_types=1);

namespace Converge\Foundation\System;

use Converge\Contracts\DatabaseInterface;
use PDO;
use PDOStatement;

class PgsqlAdapter implements DatabaseInterface
{
    private readonly PDO $pdo;

    public function __construct(
        string $host,
        string $user,
        string $password,
        string $database,
        int    $port = 5432,
    ) {
        $dsn = "pgsql:host={$host};port={$port};dbname={$database}";
        $this->pdo = new PDO($dsn, $user, $password, [
            PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES   => false,
        ]);
        $this->pdo->exec("SET NAMES 'UTF8'");
    }

    public function query(string $sql): mixed
    {
        try {
            return $this->pdo->query($sql);
        } catch (\PDOException $e) {
            throw new \RuntimeException("PostgreSQL 错误: {$e->getMessage()} [{$sql}]");
        }
    }

    public function prepare(string $sql): mixed
    {
        try {
            return $this->pdo->prepare($sql);
        } catch (\PDOException $e) {
            throw new \RuntimeException("PostgreSQL prepare 错误: {$e->getMessage()}");
        }
    }

    public function escape(string $value): string
    {
        return $this->pdo->quote($value);
    }

    public function lastInsertId(): int
    {
        return (int) $this->pdo->lastInsertId();
    }

    public function affectedRows(): int
    {
        // PDOStatement::rowCount() must be called after execute(), not on PDO itself.
        // This returns the last statement's row count if available.
        return 0; // rowCount() is per-statement in PDO, not per-connection like mysqli
    }

    public function raw(): mixed
    {
        return $this->pdo;
    }

    // ═══ PostgreSQL 特有方法 (非接口, 便利扩展) ═══

    /** 获取 PostgreSQL 版本 */
    public function version(): string
    {
        return $this->pdo->query('SELECT version()')->fetchColumn();
    }

    /** 检查表是否存在 */
    public function tableExists(string $tableName): bool
    {
        $stmt = $this->pdo->prepare(
            "SELECT EXISTS(SELECT 1 FROM information_schema.tables WHERE table_name = ?)"
        );
        $stmt->execute([$tableName]);
        return (bool) $stmt->fetchColumn();
    }
}
