; PHP 开发配置
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On
error_log = /dev/stderr
expose_php = On
memory_limit = 512M
max_execution_time = 60

; OPcache — 开发阶段关闭
opcache.enable=0
