<?php

declare(strict_types=1);

/**
 * Tailwind Grid Gate — detects bypasses of the Grid::row() / Grid::col() component.
 *
 * Rules:
 *   1. In views (.php files in resources/views/ or public/), direct use of
 *      Tailwind grid classes (grid-cols-*, col-span-*) is a violation unless
 *      the file is the Grid component itself.
 *   2. Inline grid styles are also flagged.
 *
 * Usage:
 *   php ci/check-tailwind-grid.php           # scan all views
 *   php ci/check-tailwind-grid.php --strict  # blocking exit code
 *
 * Exit codes: 0 = clean, 1 = violations found (--strict mode blocks)
 */

$strict = in_array('--strict', $argv, true);
$baseDir = dirname(__DIR__);
$violations = [];

$scanDirs = [
    $baseDir . '/resources/views',
    $baseDir . '/public',
];

$excludeFiles = [
    'check-tailwind-grid.php',
    'Grid.php',
    'tailwind.config.js',
    'tailwind-input.css',
    'design-tokens.css',
];

// Layout files use grid-cols-12 as page-level structure — allowed.
$excludeDirs = [
    'resources/views/layout',
];

// Page-level entry points — grid is structural container, not component-level
$excludePageFiles = [
    'landing.php',
    'pricing.php',
];

foreach ($scanDirs as $dir) {
    if (!is_dir($dir)) {
        continue;
    }
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($dir, RecursiveDirectoryIterator::SKIP_DOTS)
    );
    foreach ($iterator as $file) {
        if ($file->getExtension() !== 'php') {
            continue;
        }
        $path = $file->getPathname();
        $basename = $file->getFilename();

        if (in_array($basename, $excludeFiles, true) || in_array($basename, $excludePageFiles, true)) {
            continue;
        }

        // Skip layout directory — page-level grid is structural, not component-level
        $relPath = str_replace('\\', '/', str_replace($baseDir . '/', '', $path));
        $skip = false;
        foreach ($excludeDirs as $exDir) {
            if (str_starts_with($relPath, $exDir)) {
                $skip = true;
                break;
            }
        }
        if ($skip) continue;

        $content = file_get_contents($path);
        $lines = explode("\n", $content);

        // Rule 1: Direct grid-cols-* classes outside Grid component context
        if (preg_match_all('/class="[^"]*\bgrid-cols-\d+\b[^"]*"/', $content, $matches)) {
            foreach ($matches[0] as $match) {
                // Skip if the file already uses Grid::row() (might be legacy with both)
                $violations[] = [
                    'file' => str_replace($baseDir . '/', '', $path),
                    'rule' => 'raw-grid-cols',
                    'detail' => "Direct 'grid-cols-*' class — use Grid::row() instead: {$match}",
                ];
            }
        }

        // Rule 2: Direct col-span-* classes outside Grid::col() context
        // (check that the file doesn't contain Grid::col — if it does, the
        // col-span-* classes are likely generated by the component)
        $hasGridCol = str_contains($content, 'Grid::col');
        if (!$hasGridCol && preg_match_all('/class="[^"]*\bcol-span-\d+\b[^"]*"/', $content, $matches)) {
            foreach ($matches[0] as $match) {
                $violations[] = [
                    'file' => str_replace($baseDir . '/', '', $path),
                    'rule' => 'raw-col-span',
                    'detail' => "Direct 'col-span-*' class — use Grid::col() instead: {$match}",
                ];
            }
        }
    }
}

// Output
if (empty($violations)) {
    echo "  ✅ Grid component: all views use Grid::row() / Grid::col()\n";
    exit(0);
}

echo "  ⚠️  Grid component bypasses: " . count($violations) . " violation(s)\n";
foreach ($violations as $v) {
    echo "    {$v['file']}: {$v['detail']}\n";
}

exit($strict ? 1 : 0);
