<?php
// Generate PageContract files for all pages
$contractsDir = __DIR__ . '/../contracts/pages';

$contracts = [
    'attribution' => ['headExtra?' => ['type' => 'string'], 'pageHeader?' => ['type' => 'string'], 'statCardsHtml?' => ['type' => 'string'], 'modelCards?' => ['type' => 'array'], 'currentModel?' => ['type' => 'string'], 'statsHtml?' => ['type' => 'string']],
    'audit-trail' => ['headExtra?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'title?' => ['type' => 'string'], 'assetBase?' => ['type' => 'string']],
    'billing' => ['headExtra?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'title?' => ['type' => 'string'], 'assetBase?' => ['type' => 'string']],
    'campaign-stats-legacy' => ['lang?' => ['type' => 'string'], 'title?' => ['type' => 'string'], 'assetBase?' => ['type' => 'string'], 'headExtra?' => ['type' => 'string']],
    'case-studies' => ['headExtra?' => ['type' => 'string'], 'pageTitle?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'assetBase?' => ['type' => 'string'], 'title?' => ['type' => 'string'], 'profileClicks?' => ['type' => 'string|int|float'], 'profileConversions?' => ['type' => 'string|int|float'], 'profileActiveCampaigns?' => ['type' => 'string|int|float'], 'profileTier?' => ['type' => 'string'], 'forYouTitle?' => ['type' => 'string'], 'forYouProblem?' => ['type' => 'string'], 'forYouSolution?' => ['type' => 'string'], 'forYouSteps?' => ['type' => 'string'], 'forYouResult?' => ['type' => 'string'], 'forYouTip?' => ['type' => 'string'], 'library?' => ['type' => 'array']],
    'click-lookup' => ['headExtra?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'title?' => ['type' => 'string'], 'assetBase?' => ['type' => 'string']],
    'conversions' => ['headExtra?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'title?' => ['type' => 'string'], 'assetBase?' => ['type' => 'string'], 'pageTitle?' => ['type' => 'string'], 'pageDesc?' => ['type' => 'string'], 'datePresetsHtml?' => ['type' => 'string'], 'filterFormHtml?' => ['type' => 'string'], 'statsCardsHtml?' => ['type' => 'string'], 'topPaginationHtml?' => ['type' => 'string'], 'tableHtml?' => ['type' => 'string'], 'bottomPaginationHtml?' => ['type' => 'string'], 'jsVars?' => ['type' => 'string'], 'conversionDatePresetsJson?' => ['type' => 'string']],
    'docs' => ['headExtra?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'zh?' => ['type' => 'bool'], 'otherLang?' => ['type' => 'string'], 'pageTitle?' => ['type' => 'string'], 'pageDesc?' => ['type' => 'string'], 'nav?' => ['type' => 'array'], 'apis?' => ['type' => 'array']],
    'experiments' => ['headExtra?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'title?' => ['type' => 'string'], 'assetBase?' => ['type' => 'string'], 'tests?' => ['type' => 'array']],
    'forgot-password' => ['headExtra?' => ['type' => 'string'], 'pageTitle?' => ['type' => 'string'], 'heading?' => ['type' => 'string'], 'desc?' => ['type' => 'string'], 'error?' => ['type' => 'string'], 'success?' => ['type' => 'string'], 'emailLabel?' => ['type' => 'string'], 'emailValue?' => ['type' => 'string'], 'sendBtnLabel?' => ['type' => 'string'], 'backLoginLabel?' => ['type' => 'string'], 'csrfField?' => ['type' => 'string'], 'baseUrl?' => ['type' => 'string']],
    'funnel' => ['headExtra?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'title?' => ['type' => 'string'], 'assetBase?' => ['type' => 'string'], 'totalClicks?' => ['type' => 'string|int|float'], 'lpClicks?' => ['type' => 'string|int|float'], 'convs?' => ['type' => 'string|int|float'], 'rev?' => ['type' => 'string|int|float'], 'cost?' => ['type' => 'string|int|float'], 'countries?' => ['type' => 'array'], 'devices?' => ['type' => 'array'], 'suggestions?' => ['type' => 'array']],
    'funnel-builder-v2' => ['headExtra?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'title?' => ['type' => 'string'], 'assetBase?' => ['type' => 'string'], 'content?' => ['type' => 'string']],
    'hooks-dashboard' => ['headExtra?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'title?' => ['type' => 'string'], 'assetBase?' => ['type' => 'string'], 'content?' => ['type' => 'string']],
    'index' => ['lang?' => ['type' => 'string'], 'page?' => ['type' => 'int'], 'title?' => ['type' => 'string'], 'headExtra?' => ['type' => 'string'], 'kpis?' => ['type' => 'array'], 'insights?' => ['type' => 'array'], 'trendData?' => ['type' => 'array'], 'trendJson?' => ['type' => 'string'], 'recentActivity?' => ['type' => 'array'], 'campaigns?' => ['type' => 'array'], 'campaignsJson?' => ['type' => 'string'], 'stats?' => ['type' => 'array'], 'newCampaignLabel?' => ['type' => 'string'], 'pageInfoJson?' => ['type' => 'string'], 'campaign?' => ['type' => 'array'], 'chartJson?' => ['type' => 'string'], 'flowData?' => ['type' => 'array']],
    'landing-builder' => ['headExtra?' => ['type' => 'string'], 'pageHeader?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'zh?' => ['type' => 'bool'], 'alpineData?' => ['type' => 'string'], 'defaultSections?' => ['type' => 'array'], 'emptyStateHtml?' => ['type' => 'string'], 'tailwindCdn?' => ['type' => 'bool']],
    'landing-pages' => ['headExtra?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'title?' => ['type' => 'string'], 'assetBase?' => ['type' => 'string']],
    'login' => ['headExtra?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'zh?' => ['type' => 'bool'], 'otherLang?' => ['type' => 'string'], 'email?' => ['type' => 'string'], 'error?' => ['type' => 'string'], 'pageTitle?' => ['type' => 'string'], 'subtitle?' => ['type' => 'string'], 'emailLabel?' => ['type' => 'string'], 'passwordLabel?' => ['type' => 'string'], 'submitLabel?' => ['type' => 'string'], 'forgotLabel?' => ['type' => 'string'], 'signupLabel?' => ['type' => 'string']],
    'offers' => ['headExtra?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'title?' => ['type' => 'string'], 'assetBase?' => ['type' => 'string'], 'action?' => ['type' => 'string'], 'pageHeader?' => ['type' => 'string'], 'successHtml?' => ['type' => 'string'], 'errorHtml?' => ['type' => 'string'], 'listHtml?' => ['type' => 'string'], 'formHtml?' => ['type' => 'string'], 'modalScriptHtml?' => ['type' => 'string']],
    'postback-urls' => ['headExtra?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'title?' => ['type' => 'string'], 'assetBase?' => ['type' => 'string']],
    'pricing' => ['headExtra?' => ['type' => 'string'], 'title?' => ['type' => 'string'], 'plans?' => ['type' => 'array'], 'assetBase?' => ['type' => 'string']],
    'privacy' => ['headExtra?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'zh?' => ['type' => 'bool'], 'otherLang?' => ['type' => 'string'], 'pageTitle?' => ['type' => 'string']],
    'realtime-stats' => ['headExtra?' => ['type' => 'string'], 'pageHeader?' => ['type' => 'string'], 'statCardsHtml?' => ['type' => 'string'], 'campaignId?' => ['type' => 'string|int|float'], 'apiKey?' => ['type' => 'string']],
    'reset-password' => ['headExtra?' => ['type' => 'string'], 'pageTitle?' => ['type' => 'string'], 'error?' => ['type' => 'string'], 'success?' => ['type' => 'string'], 'token?' => ['type' => 'string'], 'tokenValid?' => ['type' => 'bool'], 'email?' => ['type' => 'string'], 'csrfField?' => ['type' => 'string'], 'baseUrl?' => ['type' => 'string']],
    'short-links' => ['headExtra?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'title?' => ['type' => 'string'], 'assetBase?' => ['type' => 'string'], 'pageHeader?' => ['type' => 'string'], 'badgeHtml?' => ['type' => 'string'], 'cardHtml?' => ['type' => 'string'], 'error?' => ['type' => 'string']],
    'smart-rotation' => ['headExtra?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'title?' => ['type' => 'string'], 'assetBase?' => ['type' => 'string'], 'content?' => ['type' => 'string']],
    'snapshot-viewer' => ['headExtra?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'title?' => ['type' => 'string'], 'assetBase?' => ['type' => 'string'], 'rounds?' => ['type' => 'array'], 'roundLinks?' => ['type' => 'string'], 'selected?' => ['type' => 'string'], 'hasSelectedDir?' => ['type' => 'bool'], 'summaryRowHtml?' => ['type' => 'string'], 'pageRowHtml?' => ['type' => 'string'], 'emptyCardHtml?' => ['type' => 'string']],
    'subscription' => ['headExtra?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'title?' => ['type' => 'string'], 'assetBase?' => ['type' => 'string'], 'pageHeader?' => ['type' => 'string'], 'planName?' => ['type' => 'string'], 'planPrice?' => ['type' => 'string'], 'planSources?' => ['type' => 'string'], 'planMembers?' => ['type' => 'string'], 'planAttribution?' => ['type' => 'string'], 'planApi?' => ['type' => 'string'], 'planSupport?' => ['type' => 'string'], 'planSlug?' => ['type' => 'string'], 'isFreePlan?' => ['type' => 'bool'], 'isProPlan?' => ['type' => 'bool'], 'isUnlimited?' => ['type' => 'bool'], 'conversionsUsed?' => ['type' => 'string|int|float'], 'conversionsLimit?' => ['type' => 'string|int|float'], 'usagePct?' => ['type' => 'string|int|float'], 'usageBarWidth?' => ['type' => 'string|int|float'], 'isOver?' => ['type' => 'bool'], 'invoiceRows?' => ['type' => 'array'], 'allPlans?' => ['type' => 'array']],
    'terms' => ['headExtra?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'zh?' => ['type' => 'bool'], 'otherLang?' => ['type' => 'string'], 'pageTitle?' => ['type' => 'string']],
    'traffic-sources' => ['headExtra?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'title?' => ['type' => 'string'], 'assetBase?' => ['type' => 'string']],
    'user-flow-dashboard' => ['headExtra?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'title?' => ['type' => 'string'], 'assetBase?' => ['type' => 'string'], 'content?' => ['type' => 'string']],
    'visitors' => ['headExtra?' => ['type' => 'string'], 'lang?' => ['type' => 'string'], 'title?' => ['type' => 'string'], 'assetBase?' => ['type' => 'string']],
];

$count = 0;
foreach ($contracts as $name => $fields) {
    $file = $contractsDir . '/' . $name . '.php';
    $lines = ["<?php", "", "return ["];
    foreach ($fields as $key => $def) {
        $lines[] = "    '{$key}' => ['type' => '{$def['type']}'],";
    }
    $lines[] = "];";
    file_put_contents($file, implode("\n", $lines) . "\n");
    $count++;
}

echo "Created {$count} PageContract files\n";
